# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D100 V3 tabbed.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 1080)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_tools = QtWidgets.QTabWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_tools.sizePolicy().hasHeightForWidth())
        self.tabWidget_tools.setSizePolicy(sizePolicy)
        self.tabWidget_tools.setMinimumSize(QtCore.QSize(0, 360))
        self.tabWidget_tools.setTabBarAutoHide(True)
        self.tabWidget_tools.setObjectName("tabWidget_tools")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 924, 1010))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_character_select = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_character_select.sizePolicy().hasHeightForWidth())
        self.comboBox_character_select.setSizePolicy(sizePolicy)
        self.comboBox_character_select.setEditable(False)
        self.comboBox_character_select.setObjectName("comboBox_character_select")
        self.comboBox_character_select.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_character_select, 4, 0, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(13, 13, 13, 13)
        self.horizontalLayout_6.setSpacing(13)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_general_dice_negative = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_general_dice_negative.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_general_dice_negative.setObjectName("pushButton_general_dice_negative")
        self.horizontalLayout_17.addWidget(self.pushButton_general_dice_negative)
        self.spinBox_general_dice = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_general_dice.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_general_dice.setMinimum(2)
        self.spinBox_general_dice.setMaximum(100)
        self.spinBox_general_dice.setProperty("value", 100)
        self.spinBox_general_dice.setObjectName("spinBox_general_dice")
        self.horizontalLayout_17.addWidget(self.spinBox_general_dice)
        self.pushButton_general_dice_positive = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_general_dice_positive.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_general_dice_positive.setObjectName("pushButton_general_dice_positive")
        self.horizontalLayout_17.addWidget(self.pushButton_general_dice_positive)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_17)
        self.pushButton_general_dice = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_general_dice.sizePolicy().hasHeightForWidth())
        self.pushButton_general_dice.setSizePolicy(sizePolicy)
        self.pushButton_general_dice.setObjectName("pushButton_general_dice")
        self.horizontalLayout_6.addWidget(self.pushButton_general_dice)
        self.label_general_dice = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_general_dice.sizePolicy().hasHeightForWidth())
        self.label_general_dice.setSizePolicy(sizePolicy)
        self.label_general_dice.setFrameShape(QtWidgets.QFrame.Box)
        self.label_general_dice.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_general_dice.setAlignment(QtCore.Qt.AlignCenter)
        self.label_general_dice.setObjectName("label_general_dice")
        self.horizontalLayout_6.addWidget(self.label_general_dice)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 3, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(13, 13, 13, 13)
        self.verticalLayout_9.setSpacing(13)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_character_score = QtWidgets.QLabel(self.groupBox_3)
        self.label_character_score.setAlignment(QtCore.Qt.AlignCenter)
        self.label_character_score.setObjectName("label_character_score")
        self.verticalLayout_9.addWidget(self.label_character_score)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_bonus_malus_negative = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bonus_malus_negative.sizePolicy().hasHeightForWidth())
        self.pushButton_bonus_malus_negative.setSizePolicy(sizePolicy)
        self.pushButton_bonus_malus_negative.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_bonus_malus_negative.setObjectName("pushButton_bonus_malus_negative")
        self.horizontalLayout_13.addWidget(self.pushButton_bonus_malus_negative)
        self.spinBox_character_bonus_malus = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_character_bonus_malus.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_character_bonus_malus.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_character_bonus_malus.setSuffix(" Delta")
        self.spinBox_character_bonus_malus.setPrefix("")
        self.spinBox_character_bonus_malus.setMinimum(-50)
        self.spinBox_character_bonus_malus.setMaximum(50)
        self.spinBox_character_bonus_malus.setSingleStep(5)
        self.spinBox_character_bonus_malus.setObjectName("spinBox_character_bonus_malus")
        self.horizontalLayout_13.addWidget(self.spinBox_character_bonus_malus)
        self.pushButton_bonus_malus_positive = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bonus_malus_positive.sizePolicy().hasHeightForWidth())
        self.pushButton_bonus_malus_positive.setSizePolicy(sizePolicy)
        self.pushButton_bonus_malus_positive.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_bonus_malus_positive.setObjectName("pushButton_bonus_malus_positive")
        self.horizontalLayout_13.addWidget(self.pushButton_bonus_malus_positive)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.pushButton_physic = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_physic.setObjectName("pushButton_physic")
        self.verticalLayout_9.addWidget(self.pushButton_physic)
        self.pushButton_social = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_social.setObjectName("pushButton_social")
        self.verticalLayout_9.addWidget(self.pushButton_social)
        self.pushButton_mental = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_mental.setObjectName("pushButton_mental")
        self.verticalLayout_9.addWidget(self.pushButton_mental)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(13, 13, 13, 13)
        self.verticalLayout.setSpacing(13)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_character_damage_score = QtWidgets.QLabel(self.frame)
        self.label_character_damage_score.setAlignment(QtCore.Qt.AlignCenter)
        self.label_character_damage_score.setObjectName("label_character_damage_score")
        self.verticalLayout.addWidget(self.label_character_damage_score)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_character_damage_dice_number_negative = QtWidgets.QPushButton(self.frame)
        self.pushButton_character_damage_dice_number_negative.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_character_damage_dice_number_negative.setObjectName("pushButton_character_damage_dice_number_negative")
        self.horizontalLayout_14.addWidget(self.pushButton_character_damage_dice_number_negative)
        self.spinBox_character_damage_dice_number = QtWidgets.QSpinBox(self.frame)
        self.spinBox_character_damage_dice_number.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_character_damage_dice_number.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_character_damage_dice_number.setMinimum(1)
        self.spinBox_character_damage_dice_number.setMaximum(13)
        self.spinBox_character_damage_dice_number.setObjectName("spinBox_character_damage_dice_number")
        self.horizontalLayout_14.addWidget(self.spinBox_character_damage_dice_number)
        self.pushButton_character_damage_dice_number_positive = QtWidgets.QPushButton(self.frame)
        self.pushButton_character_damage_dice_number_positive.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_character_damage_dice_number_positive.setObjectName("pushButton_character_damage_dice_number_positive")
        self.horizontalLayout_14.addWidget(self.pushButton_character_damage_dice_number_positive)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_character_damage_dice_negative = QtWidgets.QPushButton(self.frame)
        self.pushButton_character_damage_dice_negative.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_character_damage_dice_negative.setObjectName("pushButton_character_damage_dice_negative")
        self.horizontalLayout_15.addWidget(self.pushButton_character_damage_dice_negative)
        self.spinBox_character_damage_dice = QtWidgets.QSpinBox(self.frame)
        self.spinBox_character_damage_dice.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_character_damage_dice.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_character_damage_dice.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_character_damage_dice.setMinimum(2)
        self.spinBox_character_damage_dice.setMaximum(100)
        self.spinBox_character_damage_dice.setSingleStep(1)
        self.spinBox_character_damage_dice.setProperty("value", 6)
        self.spinBox_character_damage_dice.setObjectName("spinBox_character_damage_dice")
        self.horizontalLayout_15.addWidget(self.spinBox_character_damage_dice)
        self.pushButton_character_damage_dice_positive = QtWidgets.QPushButton(self.frame)
        self.pushButton_character_damage_dice_positive.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_character_damage_dice_positive.setObjectName("pushButton_character_damage_dice_positive")
        self.horizontalLayout_15.addWidget(self.pushButton_character_damage_dice_positive)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_character_damage_dice_supplement_negative = QtWidgets.QPushButton(self.frame)
        self.pushButton_character_damage_dice_supplement_negative.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_character_damage_dice_supplement_negative.setObjectName("pushButton_character_damage_dice_supplement_negative")
        self.horizontalLayout_16.addWidget(self.pushButton_character_damage_dice_supplement_negative)
        self.spinBox_character_damage_dice_supplement = QtWidgets.QSpinBox(self.frame)
        self.spinBox_character_damage_dice_supplement.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_character_damage_dice_supplement.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_character_damage_dice_supplement.setMinimum(-20)
        self.spinBox_character_damage_dice_supplement.setMaximum(20)
        self.spinBox_character_damage_dice_supplement.setObjectName("spinBox_character_damage_dice_supplement")
        self.horizontalLayout_16.addWidget(self.spinBox_character_damage_dice_supplement)
        self.pushButton_character_damage_dice_supplement_positive = QtWidgets.QPushButton(self.frame)
        self.pushButton_character_damage_dice_supplement_positive.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_character_damage_dice_supplement_positive.setObjectName("pushButton_character_damage_dice_supplement_positive")
        self.horizontalLayout_16.addWidget(self.pushButton_character_damage_dice_supplement_positive)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_character_damage = QtWidgets.QPushButton(self.frame)
        self.pushButton_character_damage.setObjectName("pushButton_character_damage")
        self.horizontalLayout_9.addWidget(self.pushButton_character_damage)
        self.pushButton_character_damage_max = QtWidgets.QPushButton(self.frame)
        self.pushButton_character_damage_max.setObjectName("pushButton_character_damage_max")
        self.horizontalLayout_9.addWidget(self.pushButton_character_damage_max)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 5, 0, 1, 2)
        self.line_general = QtWidgets.QFrame(self.groupBox_3)
        self.line_general.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_general.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_general.setObjectName("line_general")
        self.gridLayout_6.addWidget(self.line_general, 2, 0, 1, 1)
        self.label_general_info = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_general_info.sizePolicy().hasHeightForWidth())
        self.label_general_info.setSizePolicy(sizePolicy)
        self.label_general_info.setMinimumSize(QtCore.QSize(0, 42))
        self.label_general_info.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_general_info.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_general_info.setLineWidth(3)
        self.label_general_info.setMidLineWidth(3)
        self.label_general_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_general_info.setObjectName("label_general_info")
        self.gridLayout_6.addWidget(self.label_general_info, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_adventure = QtWidgets.QFrame(self.frame_4)
        self.line_adventure.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_adventure.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_adventure.setObjectName("line_adventure")
        self.gridLayout_5.addWidget(self.line_adventure, 1, 0, 1, 1)
        self.label_adventure_result = QtWidgets.QLabel(self.frame_4)
        self.label_adventure_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adventure_result.setObjectName("label_adventure_result")
        self.gridLayout_5.addWidget(self.label_adventure_result, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_adventure_GM = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_adventure_GM.setObjectName("pushButton_adventure_GM")
        self.horizontalLayout_3.addWidget(self.pushButton_adventure_GM)
        self.pushButton_adventure_PC = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_adventure_PC.setObjectName("pushButton_adventure_PC")
        self.horizontalLayout_3.addWidget(self.pushButton_adventure_PC)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalSlider_adventure_counter = QtWidgets.QSlider(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_adventure_counter.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_adventure_counter.setSizePolicy(sizePolicy)
        self.horizontalSlider_adventure_counter.setMinimum(1)
        self.horizontalSlider_adventure_counter.setMaximum(5)
        self.horizontalSlider_adventure_counter.setPageStep(1)
        self.horizontalSlider_adventure_counter.setProperty("value", 3)
        self.horizontalSlider_adventure_counter.setSliderPosition(3)
        self.horizontalSlider_adventure_counter.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_adventure_counter.setObjectName("horizontalSlider_adventure_counter")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_adventure_counter)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_GM = QtWidgets.QLabel(self.frame_4)
        self.label_GM.setObjectName("label_GM")
        self.horizontalLayout_5.addWidget(self.label_GM)
        self.label_adventure_counter = QtWidgets.QLabel(self.frame_4)
        self.label_adventure_counter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adventure_counter.setObjectName("label_adventure_counter")
        self.horizontalLayout_5.addWidget(self.label_adventure_counter)
        self.label_PC = QtWidgets.QLabel(self.frame_4)
        self.label_PC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_PC.setObjectName("label_PC")
        self.horizontalLayout_5.addWidget(self.label_PC)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.label_adventure_title = QtWidgets.QLabel(self.frame_4)
        self.label_adventure_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adventure_title.setWordWrap(False)
        self.label_adventure_title.setObjectName("label_adventure_title")
        self.gridLayout_5.addWidget(self.label_adventure_title, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 2, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalSlider_timer_set_time = QtWidgets.QSlider(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_timer_set_time.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_timer_set_time.setSizePolicy(sizePolicy)
        self.horizontalSlider_timer_set_time.setMinimum(1)
        self.horizontalSlider_timer_set_time.setMaximum(60)
        self.horizontalSlider_timer_set_time.setProperty("value", 15)
        self.horizontalSlider_timer_set_time.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_timer_set_time.setObjectName("horizontalSlider_timer_set_time")
        self.gridLayout_8.addWidget(self.horizontalSlider_timer_set_time, 10, 0, 1, 1)
        self.pushButton_timer_random = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_timer_random.setObjectName("pushButton_timer_random")
        self.gridLayout_8.addWidget(self.pushButton_timer_random, 13, 0, 1, 1)
        self.pushButton_timer_fixed = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_timer_fixed.setObjectName("pushButton_timer_fixed")
        self.gridLayout_8.addWidget(self.pushButton_timer_fixed, 12, 0, 1, 1)
        self.label_timer_set_time = QtWidgets.QLabel(self.frame_5)
        self.label_timer_set_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_timer_set_time.setObjectName("label_timer_set_time")
        self.gridLayout_8.addWidget(self.label_timer_set_time, 9, 0, 1, 1)
        self.label_timer = QtWidgets.QLabel(self.frame_5)
        self.label_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_timer.setObjectName("label_timer")
        self.gridLayout_8.addWidget(self.label_timer, 5, 0, 1, 1)
        self.label_timer_title = QtWidgets.QLabel(self.frame_5)
        self.label_timer_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_timer_title.setObjectName("label_timer_title")
        self.gridLayout_8.addWidget(self.label_timer_title, 0, 0, 1, 1)
        self.comboBox_timer_events = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_timer_events.setObjectName("comboBox_timer_events")
        self.comboBox_timer_events.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_timer_events, 11, 0, 1, 1)
        self.line_timer_title = QtWidgets.QFrame(self.frame_5)
        self.line_timer_title.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_timer_title.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_timer_title.setObjectName("line_timer_title")
        self.gridLayout_8.addWidget(self.line_timer_title, 1, 0, 1, 1)
        self.progressBar_timer = QtWidgets.QProgressBar(self.frame_5)
        self.progressBar_timer.setObjectName("progressBar_timer")
        self.gridLayout_8.addWidget(self.progressBar_timer, 7, 0, 1, 1)
        self.line_timer = QtWidgets.QFrame(self.frame_5)
        self.line_timer.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_timer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_timer.setObjectName("line_timer")
        self.gridLayout_8.addWidget(self.line_timer, 8, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_4.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.gridLayout_10.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget_tools.addTab(self.tab, "")
        self.tabWidget_player = QtWidgets.QWidget()
        self.tabWidget_player.setObjectName("tabWidget_player")
        self.gridLayout = QtWidgets.QGridLayout(self.tabWidget_player)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_players = QtWidgets.QTableWidget(self.tabWidget_player)
        self.tableWidget_players.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_players.setObjectName("tableWidget_players")
        self.tableWidget_players.setColumnCount(0)
        self.tableWidget_players.setRowCount(0)
        self.tableWidget_players.horizontalHeader().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.tableWidget_players, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_remove_player = QtWidgets.QPushButton(self.tabWidget_player)
        self.pushButton_remove_player.setObjectName("pushButton_remove_player")
        self.horizontalLayout_12.addWidget(self.pushButton_remove_player)
        self.pushButton_add_player = QtWidgets.QPushButton(self.tabWidget_player)
        self.pushButton_add_player.setObjectName("pushButton_add_player")
        self.horizontalLayout_12.addWidget(self.pushButton_add_player)
        self.gridLayout.addLayout(self.horizontalLayout_12, 3, 0, 1, 1)
        self.tabWidget_tools.addTab(self.tabWidget_player, "")
        self.tabWidget_npc_story = QtWidgets.QWidget()
        self.tabWidget_npc_story.setObjectName("tabWidget_npc_story")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tabWidget_npc_story)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tableWidget_npc_story = QtWidgets.QTableWidget(self.tabWidget_npc_story)
        self.tableWidget_npc_story.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_npc_story.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_npc_story.setObjectName("tableWidget_npc_story")
        self.tableWidget_npc_story.setColumnCount(0)
        self.tableWidget_npc_story.setRowCount(0)
        self.tableWidget_npc_story.horizontalHeader().setCascadingSectionResizes(True)
        self.horizontalLayout_7.addWidget(self.tableWidget_npc_story)
        self.gridLayout_12.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(13, 13, 13, 13)
        self.horizontalLayout_10.setSpacing(13)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem2)
        self.pushButton_suppress_all_npc_story = QtWidgets.QPushButton(self.tabWidget_npc_story)
        self.pushButton_suppress_all_npc_story.setObjectName("pushButton_suppress_all_npc_story")
        self.verticalLayout_7.addWidget(self.pushButton_suppress_all_npc_story)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.line_2 = QtWidgets.QFrame(self.tabWidget_npc_story)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_18.addWidget(self.line_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem4)
        self.pushButton_add_npc_story = QtWidgets.QPushButton(self.tabWidget_npc_story)
        self.pushButton_add_npc_story.setObjectName("pushButton_add_npc_story")
        self.verticalLayout_6.addWidget(self.pushButton_add_npc_story)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tabWidget_npc_story)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.comboBox_generate_npc_story = QtWidgets.QComboBox(self.tabWidget_npc_story)
        self.comboBox_generate_npc_story.setObjectName("comboBox_generate_npc_story")
        self.verticalLayout_3.addWidget(self.comboBox_generate_npc_story)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_max_npc_story = QtWidgets.QLabel(self.tabWidget_npc_story)
        self.label_max_npc_story.setAlignment(QtCore.Qt.AlignCenter)
        self.label_max_npc_story.setObjectName("label_max_npc_story")
        self.verticalLayout_21.addWidget(self.label_max_npc_story)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_max_npc_story_spawn_negative = QtWidgets.QPushButton(self.tabWidget_npc_story)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_max_npc_story_spawn_negative.sizePolicy().hasHeightForWidth())
        self.pushButton_max_npc_story_spawn_negative.setSizePolicy(sizePolicy)
        self.pushButton_max_npc_story_spawn_negative.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_max_npc_story_spawn_negative.setObjectName("pushButton_max_npc_story_spawn_negative")
        self.horizontalLayout_19.addWidget(self.pushButton_max_npc_story_spawn_negative)
        self.spinBox_max_npc_story_spawn = QtWidgets.QSpinBox(self.tabWidget_npc_story)
        self.spinBox_max_npc_story_spawn.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_max_npc_story_spawn.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_max_npc_story_spawn.setMinimum(1)
        self.spinBox_max_npc_story_spawn.setMaximum(10)
        self.spinBox_max_npc_story_spawn.setProperty("value", 5)
        self.spinBox_max_npc_story_spawn.setObjectName("spinBox_max_npc_story_spawn")
        self.horizontalLayout_19.addWidget(self.spinBox_max_npc_story_spawn)
        self.pushButton_max_npc_story_spawn_positive = QtWidgets.QPushButton(self.tabWidget_npc_story)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.pushButton_max_npc_story_spawn_positive.sizePolicy().hasHeightForWidth())
        self.pushButton_max_npc_story_spawn_positive.setSizePolicy(sizePolicy)
        self.pushButton_max_npc_story_spawn_positive.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_max_npc_story_spawn_positive.setToolTipDuration(0)
        self.pushButton_max_npc_story_spawn_positive.setObjectName("pushButton_max_npc_story_spawn_positive")
        self.horizontalLayout_19.addWidget(self.pushButton_max_npc_story_spawn_positive)
        self.verticalLayout_21.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_10.addLayout(self.verticalLayout_21)
        self.gridLayout_12.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.tabWidget_tools.addTab(self.tabWidget_npc_story, "")
        self.tabWidget_npc_combat = QtWidgets.QWidget()
        self.tabWidget_npc_combat.setObjectName("tabWidget_npc_combat")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabWidget_npc_combat)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tableWidget_npc_combat = QtWidgets.QTableWidget(self.tabWidget_npc_combat)
        self.tableWidget_npc_combat.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_npc_combat.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_npc_combat.setObjectName("tableWidget_npc_combat")
        self.tableWidget_npc_combat.setColumnCount(0)
        self.tableWidget_npc_combat.setRowCount(0)
        self.tableWidget_npc_combat.horizontalHeader().setCascadingSectionResizes(True)
        self.horizontalLayout_8.addWidget(self.tableWidget_npc_combat)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(13, 13, 13, 13)
        self.horizontalLayout_11.setSpacing(13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem5)
        self.pushButton_suppress_all_npc_combat = QtWidgets.QPushButton(self.tabWidget_npc_combat)
        self.pushButton_suppress_all_npc_combat.setObjectName("pushButton_suppress_all_npc_combat")
        self.verticalLayout_5.addWidget(self.pushButton_suppress_all_npc_combat)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem6)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.line = QtWidgets.QFrame(self.tabWidget_npc_combat)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_21.addWidget(self.line)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem7)
        self.pushButton_add_npc_combat = QtWidgets.QPushButton(self.tabWidget_npc_combat)
        self.pushButton_add_npc_combat.setObjectName("pushButton_add_npc_combat")
        self.verticalLayout_4.addWidget(self.pushButton_add_npc_combat)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tabWidget_npc_combat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.comboBox_generate_npc_combat = QtWidgets.QComboBox(self.tabWidget_npc_combat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_generate_npc_combat.sizePolicy().hasHeightForWidth())
        self.comboBox_generate_npc_combat.setSizePolicy(sizePolicy)
        self.comboBox_generate_npc_combat.setEditable(False)
        self.comboBox_generate_npc_combat.setCurrentText("")
        self.comboBox_generate_npc_combat.setObjectName("comboBox_generate_npc_combat")
        self.verticalLayout_2.addWidget(self.comboBox_generate_npc_combat)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_max_npc_combat = QtWidgets.QLabel(self.tabWidget_npc_combat)
        self.label_max_npc_combat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_max_npc_combat.setObjectName("label_max_npc_combat")
        self.verticalLayout_22.addWidget(self.label_max_npc_combat)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pushButton_max_npc_combat_spawn_negative = QtWidgets.QPushButton(self.tabWidget_npc_combat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_max_npc_combat_spawn_negative.sizePolicy().hasHeightForWidth())
        self.pushButton_max_npc_combat_spawn_negative.setSizePolicy(sizePolicy)
        self.pushButton_max_npc_combat_spawn_negative.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_max_npc_combat_spawn_negative.setObjectName("pushButton_max_npc_combat_spawn_negative")
        self.horizontalLayout_20.addWidget(self.pushButton_max_npc_combat_spawn_negative)
        self.spinBox_max_npc_combat_spawn = QtWidgets.QSpinBox(self.tabWidget_npc_combat)
        self.spinBox_max_npc_combat_spawn.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_max_npc_combat_spawn.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_max_npc_combat_spawn.setMinimum(1)
        self.spinBox_max_npc_combat_spawn.setMaximum(10)
        self.spinBox_max_npc_combat_spawn.setProperty("value", 5)
        self.spinBox_max_npc_combat_spawn.setObjectName("spinBox_max_npc_combat_spawn")
        self.horizontalLayout_20.addWidget(self.spinBox_max_npc_combat_spawn)
        self.pushButton_max_npc_combat_spawn_positive = QtWidgets.QPushButton(self.tabWidget_npc_combat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_max_npc_combat_spawn_positive.sizePolicy().hasHeightForWidth())
        self.pushButton_max_npc_combat_spawn_positive.setSizePolicy(sizePolicy)
        self.pushButton_max_npc_combat_spawn_positive.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton_max_npc_combat_spawn_positive.setObjectName("pushButton_max_npc_combat_spawn_positive")
        self.horizontalLayout_20.addWidget(self.pushButton_max_npc_combat_spawn_positive)
        self.verticalLayout_22.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_11.addLayout(self.verticalLayout_22)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.tabWidget_tools.addTab(self.tabWidget_npc_combat, "")
        self.tabWidget_soundbox = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_soundbox.sizePolicy().hasHeightForWidth())
        self.tabWidget_soundbox.setSizePolicy(sizePolicy)
        self.tabWidget_soundbox.setObjectName("tabWidget_soundbox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabWidget_soundbox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.tabWidget_soundbox)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 924, 1010))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_soundbox = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_soundbox.setContentsMargins(32, 32, 32, 32)
        self.gridLayout_soundbox.setSpacing(32)
        self.gridLayout_soundbox.setObjectName("gridLayout_soundbox")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_7.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget_tools.addTab(self.tabWidget_soundbox, "")
        self.gridLayout_2.addWidget(self.tabWidget_tools, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.widget)
        self.actionVague_de_races_mixte = QtWidgets.QAction(MainWindow)
        self.actionVague_de_races_mixte.setObjectName("actionVague_de_races_mixte")

        self.retranslateUi(MainWindow)
        self.tabWidget_tools.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trousse du MJ"))
        self.comboBox_character_select.setCurrentText(_translate("MainWindow", "Joueur / PNJ"))
        self.comboBox_character_select.setItemText(0, _translate("MainWindow", "Joueur / PNJ"))
        self.pushButton_general_dice_negative.setText(_translate("MainWindow", "-"))
        self.spinBox_general_dice.setPrefix(_translate("MainWindow", "D"))
        self.pushButton_general_dice_positive.setText(_translate("MainWindow", "+"))
        self.pushButton_general_dice.setText(_translate("MainWindow", "Lancer dé"))
        self.label_general_dice.setText(_translate("MainWindow", "D100 : 100 "))
        self.label_character_score.setText(_translate("MainWindow", "Physique : Réussite\n"
" score = 32 / 75"))
        self.pushButton_bonus_malus_negative.setText(_translate("MainWindow", "-"))
        self.pushButton_bonus_malus_positive.setText(_translate("MainWindow", "+"))
        self.pushButton_physic.setText(_translate("MainWindow", "Physique"))
        self.pushButton_social.setText(_translate("MainWindow", "Social"))
        self.pushButton_mental.setText(_translate("MainWindow", "Mental"))
        self.label_character_damage_score.setText(_translate("MainWindow", "2D6+2\n"
"Dégâts : 5"))
        self.pushButton_character_damage_dice_number_negative.setText(_translate("MainWindow", "-"))
        self.pushButton_character_damage_dice_number_positive.setText(_translate("MainWindow", "+"))
        self.pushButton_character_damage_dice_negative.setText(_translate("MainWindow", "-"))
        self.spinBox_character_damage_dice.setPrefix(_translate("MainWindow", "D"))
        self.pushButton_character_damage_dice_positive.setText(_translate("MainWindow", "+"))
        self.pushButton_character_damage_dice_supplement_negative.setText(_translate("MainWindow", "-"))
        self.pushButton_character_damage_dice_supplement_positive.setText(_translate("MainWindow", "+"))
        self.pushButton_character_damage.setText(_translate("MainWindow", "Dégâts"))
        self.pushButton_character_damage_max.setText(_translate("MainWindow", "MAX dégâts"))
        self.label_general_info.setText(_translate("MainWindow", "PNJ 2 est mort"))
        self.label_adventure_result.setText(_translate("MainWindow", "Posture"))
        self.pushButton_adventure_GM.setText(_translate("MainWindow", "MJ"))
        self.pushButton_adventure_PC.setText(_translate("MainWindow", "PJ"))
        self.label_GM.setText(_translate("MainWindow", "MJ"))
        self.label_adventure_counter.setText(_translate("MainWindow", "3/5"))
        self.label_PC.setText(_translate("MainWindow", "PJ"))
        self.label_adventure_title.setText(_translate("MainWindow", "AVENTURE"))
        self.pushButton_timer_random.setText(_translate("MainWindow", "Aléatoire"))
        self.pushButton_timer_fixed.setText(_translate("MainWindow", "Fixe"))
        self.label_timer_set_time.setText(_translate("MainWindow", "15 minutes"))
        self.label_timer.setText(_translate("MainWindow", "Lancer un timer !"))
        self.label_timer_title.setText(_translate("MainWindow", "TIMER"))
        self.comboBox_timer_events.setItemText(0, _translate("MainWindow", "Evénements du timer"))
        self.tabWidget_tools.setTabText(self.tabWidget_tools.indexOf(self.tab), _translate("MainWindow", "Outils"))
        self.pushButton_remove_player.setText(_translate("MainWindow", "Supprimer une ligne"))
        self.pushButton_add_player.setText(_translate("MainWindow", "Ajouter une ligne"))
        self.tabWidget_tools.setTabText(self.tabWidget_tools.indexOf(self.tabWidget_player), _translate("MainWindow", "Joueurs"))
        self.pushButton_suppress_all_npc_story.setText(_translate("MainWindow", "Tout supprimer"))
        self.pushButton_add_npc_story.setText(_translate("MainWindow", "Ajouter un PNJ"))
        self.label_2.setText(_translate("MainWindow", "Générer vague de PNJs"))
        self.label_max_npc_story.setText(_translate("MainWindow", "Max PNJs par vague"))
        self.pushButton_max_npc_story_spawn_negative.setText(_translate("MainWindow", "-"))
        self.pushButton_max_npc_story_spawn_positive.setText(_translate("MainWindow", "+"))
        self.tabWidget_tools.setTabText(self.tabWidget_tools.indexOf(self.tabWidget_npc_story), _translate("MainWindow", "PNJ Histoire"))
        self.pushButton_suppress_all_npc_combat.setText(_translate("MainWindow", "Tout supprimer"))
        self.pushButton_add_npc_combat.setText(_translate("MainWindow", "Ajouter un PNJ"))
        self.label.setText(_translate("MainWindow", "Générer vague de PNJs"))
        self.label_max_npc_combat.setText(_translate("MainWindow", "Max PNJs par vague"))
        self.pushButton_max_npc_combat_spawn_negative.setText(_translate("MainWindow", "-"))
        self.pushButton_max_npc_combat_spawn_positive.setText(_translate("MainWindow", "+"))
        self.tabWidget_tools.setTabText(self.tabWidget_tools.indexOf(self.tabWidget_npc_combat), _translate("MainWindow", "PNJ Combat"))
        self.tabWidget_tools.setTabText(self.tabWidget_tools.indexOf(self.tabWidget_soundbox), _translate("MainWindow", "Soundbox"))
        self.actionVague_de_races_mixte.setText(_translate("MainWindow", "Vague de races mixte"))

